### ISSUE TITLE
Fixing for RowHeight Calculation

### ISSUE THREAD

**Issue by KamranAsif** [schrodinger/fixed-data-table-2#37]
## Goals

Change the way fixed data table handles its internal state to allow correct dynamic row height calculation## Current Behavior
## Current State
- State is stored as part of the top level react component, as well as in some children component
- Changing any portion of state re-runs _calculateState, which update scrollContentHeight from scrollHelper
- Child components, namely BufferedRows, force the row height calculation to update, meaning the contentHeight value becomes stale
- _reportContentHeight uses stale data because update state wasn’t triggered
- In certain edge cases, there is no further action to trigger subsequent call to _calculateState, leading to incorrect call to update content height
## Proposed Solution
- Remove all state in react components and add redux dependency to hold state 
- Start this process by first moving only scrolling/height related data to redux store
1. Move ScrollHelper state to redux store
   - One issue that may arise is usage of PrefixIntervalTree. Since it is a self-contained object, it may require some hacking around to return new reference. 
2. Move all ScrollHelper callbacks to actions
   - scrollRowIntoView
   - setViewportHeight
   - scrollBy
   - scrollTo
   - scrollToRow
   - setRowHeightGetter
3. Add redux react store connectors to replace ScrollHelper getters
   - getContentHeight
   - getRowPosition
4. Remove state from BufferedRows
   - We want the main table to be in charge of telling BufferedRows which ones to render
   - This will allow us to remove getRowPosition call from BufferedRows and instead precompute the     desired row heights
   - This will allow us to remove the side effect in getRowPosition so that it doesn’t update state
## Tasks
- [ ] Inject redux store logic into FDT calculateState
- [ ] Migrate scrollHelper state to redux store
- [ ] Create actions/reducers for scrollHelper setters 
- [ ] Inject store updating to replace getters
- [ ] Cleanup BufferedRows state

**Comment by JMacLulich** [comment]
If this is still a pending issue in a few weeks I'll have a bit of time to see if I can help you on this

I've got a deadline however using this component due in 2 weeks, so I'll understand a lot more about using it after then.

**Comment by KamranAsif** [comment]
I'm not sure what our timeline is but feel free to give it a crack. It should be broken up enough that we can work on it piecemeal

**Comment by wcjordan** [comment]
For anyone interested, I've published a beta release which addresses this.
To use it, set package.json to point to 1.0.0-beta.3 of fixed-data-table-2 or run `yarn add fixed-data-table-2@beta`.

Any help testing anyone can give me would be great.  Thanks!

**Comment by wcjordan** [comment]
This should be done w/ the v1.0 release
